version: '3.8'

services:
  radarninja:
    image: ghcr.io/salesioninja/radarninja:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=true
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    networks:
      - proxy

networks:
  proxy:
    external: true
